#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'hourglassSum' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY arr as parameter.
#

def hourglassSum(arr):
    # Write your code here
    array = arr.copy()
    hourglass_size = 3      # size of hourglass = 3x3
    for i in range(len(array[0])- hourglass_size +1):
        for j in range(len(array[0]) - hourglass_size +1):
            x1, x2, x3 = array[i][j], array[i][j+1], array[i][j+2]
            x4 = array[i+1][j+1]
            x5, x6, x7 = array[i+2][j], array[i+2][j+1], array[i+2][j+2]
            total = sum([x1, x2, x3, x4, x5, x6, x7])
            if (i,j) == (0,0):
                t = total
            else:
                if total>= t:
                    t = total
                else:
                    t = t
    return t

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    arr = []

    for _ in range(6):
        arr.append(list(map(int, input().rstrip().split())))

    result = hourglassSum(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
